### ISSUE TITLE
2.1.8版本插件，生成接口文档的是的int，long类型映射问题，header参数

### ISSUE THREAD

**Issue by best-one** [smart-doc-group/smart-doc-maven-plugin#10]
1、java 类型问题
    int类型在文档看到是int32，long类型看到是int64

2、header问题
   文档扫描没有扫描获取header参数，有些接口是有header参数

**Comment by netdied** [comment]
1. 根据OpanApi规范 int为int32  long int64 没啥问题。
2. 提供一下代码的样例呢？我们目前没有遇到相关问题。
