### ISSUE TITLE
泛型中的第二个参数无法识别

### ISSUE THREAD

**Issue by worker-wu** [smart-doc-group/smart-doc-maven-plugin#12]
## Expected Behavior(您期望的结果)

![image](https://user-images.githubusercontent.com/30458346/156172460-c978abfe-f31c-41be-ac8d-9006056d2b4c.png)

## Current Behavior(当前结果)

![image](https://user-images.githubusercontent.com/30458346/156172589-5e47aed5-dc89-43ce-b78f-901d7c359730.png)
![image](https://user-images.githubusercontent.com/30458346/156172522-6b08d6bc-72e5-4896-8f39-1d482f642990.png)

## Steps to Reproduce (Bug产生步骤，请尽量提供用例代码)

1.Object<T,S>这种类型的对象，无法识别S的泛型类型,T可以识别

## Context(Bug影响描述)

由于本人是结合smarc-doc + torna用于接口文档管理，有一些特殊的场景需要与C++做交互，请求报文格式由对方定义，此时想通过smart-doc + torna来维护接口文档，降低沟通成本，由于泛型中的第二个参数一直无法识别，导致文档无法正常交互

## Your Environment(您的使用环境)

spring boot(2.3.2) + smart-doc-maven-plugin(2.3.9) + torna(docker->tanghc2020/torna:latest)
代码：

**Comment by wuziyangGitHub** [comment]
# Body.java

```java
@Data
@JsonPropertyOrder({"oee", "request", "response"})
public class Body<T, R> {

    private Oee<T> oee;

    //@JsonInclude(JsonInclude.Include.NON_NULL)
    private R request;

    //@JsonInclude(JsonInclude.Include.NON_NULL)
    private R response;
}
```

# Head.java

```java
@Data
@JsonPropertyOrder({"protocol", "onlineId", "timestamp", "serialNumber", "operationType", "operationCode", "terminal"})
public class Head {

    /**
     * 协议版本号
     */
    private Integer protocol;

    /**
     * 在线id
     */
    private String onlineId;

    /**
     * 请求时间
     */
    private String timestamp;

    /**
     * 请求流水号
     */
    private String serialNumber;

    /**
     * 操作类型
     */
    private Integer operationType;

    /**
     * 操作码
     */
    private Integer operationCode;

    /**
     * 数据
     */
    private String terminal;
}

```

# Header.java

```java
@Data
@JsonPropertyOrder({"protocol", "timestamp", "requestId", "source", "strategy", "statusCode"})
public class Header {

    /**
     * 协议版本
     */
    private Integer protocol;

    /**
     * 请求时间戳
     */
    private String timestamp;

    /**
     * 请求id
     */
    private String requestId;

    /**
     * 来源
     */
    private Integer source;

    /**
     * 加密策略
     */
    private Integer strategy;

    /**
     * 状态码[0:成功 其他:失败]
     */
    private Integer statusCode;
}
```



# InteractiveProtocol.java

```java
@Data
public class InteractiveProtocol<T, R> {


    /**
     * 通信协议信息
     */
    private Header header;

    /**
     * 请求体
     */
    private Body<T, R> body;

}
```



# Oee.java

```java
@Data
@JsonPropertyOrder({"head", "data"})
public class Oee<T> {

    private Head head;

    private T data;
}
```

**Comment by wuziyangGitHub** [comment]
如果修复了这个bug，maven仓库能否deploy一下新版，现在下载的还是旧版的代码 
我需要验证一下这个结果

**Comment by netdied** [comment]
目前版本频率大概一周发布一次  急着用的话可以下dev分支的代码 install一下进行测试。

**Comment by netdied** [comment]
smart-doc 的dev分支 不是插件的

**Comment by wuziyangGitHub** [comment]
可以的  请问  大概周几能发布呢

**Comment by wuziyangGitHub** [comment]
1

**Comment by wuziyangGitHub** [comment]
自己尝试了一下，通过本地文件这个问题是解决了。但是又引申出一个新问题，当泛型<S,T>
S使用maven私服文件，T使用本地文件时又会发生如下问题，T读取错误
![image](https://user-images.githubusercontent.com/30458346/156720487-35668dc3-cfe3-4db9-a511-155cbb24d432.png)
![image](https://user-images.githubusercontent.com/30458346/156720539-cd56bbc0-3b3e-4df3-af8a-4d4f26185165.png)
![image](https://user-images.githubusercontent.com/30458346/156720567-1b9cc2ba-262e-480a-b0fc-37b2cf8b293d.png)
![image](https://user-images.githubusercontent.com/30458346/156720469-440b594e-08a0-480a-826f-381f0181b3c9.png)

方便留个方式沟通一下吗

**Comment by netdied** [comment]
QQ群：170651381 
QQ2群：537970662
