### ISSUE TITLE
Controller返回值继承（或实现）泛型类，生成的文档字段属性不对

### ISSUE THREAD

**Issue by happydevelopers** [smart-doc-group/smart-doc-maven-plugin#16]
## Expected Behavior(您期望的结果)

根据对应字段属性生成文档。

## Current Behavior(当前结果)

字段属性生成的文档不匹配。

## Steps to Reproduce (Bug产生步骤，请尽量提供用例代码)

1.
![`{OW$(EW77LNWD`9IFPG2%Q](https://user-images.githubusercontent.com/22808725/169935564-8068c125-dc00-42c8-b9d1-8c66917f7a03.jpg)

2.
![QQ截图20220524101644](https://user-images.githubusercontent.com/22808725/169935584-5d06dfa8-210f-4d8d-8fa9-f0d5dcfcda72.jpg)

3. 
![QQ截图20220524103003](https://user-images.githubusercontent.com/22808725/169936553-9bd74122-9048-4eaa-b0bd-a4dfc9edbde8.jpg)

4.
![5 3DZ$EHYKSKR_5Q2~KNWB3](https://user-images.githubusercontent.com/22808725/169935605-7d2020b1-56f7-4c96-9436-557e353fdc08.jpg)

5.
![0C3%GW{%QTMTWY1L}7_IV~5](https://user-images.githubusercontent.com/22808725/169935622-1982fdb5-ec53-4361-a6bd-f2937c9af0f2.jpg)

6. 
![QQ截图20220524103305](https://user-images.githubusercontent.com/22808725/169936785-b7c604fa-ab9e-4b9d-a871-8e0375e1e89b.jpg)

## Context(Bug影响描述)

返回值JsonResult<Page<GroupVo>>的Page实现IPage接口。
Page对象的orders字段protected List<OrderItem> orders = new ArrayList<>();，生成的文档字段成了GroupVo里面的字段属性。

## Your Environment(您的使用环境)

* smart-doc version: 2.4.5
* plugin version (e.g. smart-doc-maven-plugin or smart-doc-gradle-plugin): smart-doc-maven-plugin2.4.5
* build tool version(maven or gradle): 3.8.4

**Comment by chenqi146** [comment]
maven插件的配置中是否include了mybatis-plus的包
