### ISSUE TITLE
公共模块注释怎么提取不到

### ISSUE THREAD

**Issue by liukeqing** [smart-doc-group/smart-doc-maven-plugin#18]
## Expected Behavior(您期望的结果)
正常提取到公共模块和依赖包的注释

## Current Behavior(当前结果)
项目使用ruoyi框架。没有改动任何代码和配置。只是把版本从2.4.8升级到2.4.9。公共模块和依赖包中的注释就不能提取了。
观察日志输出，Smart-doc has loaded the source code path这段日志的输出方式发生了改变，并且打印的 source code path只有直接依赖路径，没有间接依赖路径。

## Possible Solution(bug解决建议)
观察了插件源代码，应该是代码升级，修改了逻辑，导致不能加载间接依赖的源码注释。

## Steps to Reproduce (Bug产生步骤，请尽量提供用例代码)

无

## Context(Bug影响描述)
无

## Your Environment(您的使用环境)

* smart-doc version:
* plugin version (e.g. smart-doc-maven-plugin or smart-doc-gradle-plugin): 2.4.9
* build tool version(maven or gradle): maven

**Comment by shalousun** [comment]
@liukeqing 你可以升级到最新，然后拉取smart-doc-maven-plugin最新的代码自己本地install测试下。未发布的也有一些更新，如果不行我们在对比2.4.8的代码修复下。

**Comment by liukeqing** [comment]
😂
我是升级到最新的2.5.3版本，发现这个问题的。然后，我逐个版本回退到2.4.8，这个问题没有了。查看“变更日志”也没有发现端倪。查看2.4.9的源码更新，src/main/java/com/smartdoc/util/MojoUtils.java这个文件的更新，推断可能导致这个问题。

**Comment by netdied** [comment]
2.4.9的只是更新了 源码的路径 你拉一下源码重新打包本地试下
