### ISSUE TITLE
ClassNotFoundException

### ISSUE THREAD

**Issue by lanux** [smart-doc-group/smart-doc-maven-plugin#3]
com.power.doc.builder.BaseDocBuilderTemplate#errorCodeDictToList，java.lang.Class#forName(java.lang.String)无法加载本身项目中的类

**Comment by netdied** [comment]
麻烦提供一下详细报错截图和测试用例截图

**Comment by netdied** [comment]
请参考如下模板详细描述你的问题 谢谢：
当前使用版本(必须填写清楚，否则不予处理)
1.9.0

该问题是怎么引起的(如果最新版本已经修复的，会直接关闭)？
maven依赖下载不下来

重现步骤
报错信息

**Comment by chishengfeng** [comment]
也是报这个错。我的项目是web module 依赖 common 模块。插件配置在web的pom.xml中，在使用枚举类的时候，提示找不到。

`
 "dataDictionaries": [{
    "title": "XXXXStatus枚举",
    "enumClassName": "com.xx.xx.common.enums.XxxEnum.XXXXStatus",
    "codeField": "code",
    "descField": "desc"
  }]
`

**Comment by caochaofeng** [comment]
com.power.doc.builder.BaseDocBuilderTemplate#errorCodeDictToList，java.lang.Class#forName(java.lang.String)无法加载本身项目中的类
![image](https://user-images.githubusercontent.com/5482661/93692162-25365900-fb22-11ea-8e25-79ae0da908df.png)

**Comment by netdied** [comment]
这里支持的是枚举类型类 不是接口类 且必须是双值及以上的枚举 例如：
public enum ErrorCodeEnum {
    SUCCESS("0000", "success"),

    PARAM_EMPTY("1001", "必选参数为空"),

    PARAM_ERROR("1002", "参数格式错误"),

    UNKNOWN_ERROR("9999", "系统繁忙，请稍后再试....");

    private String code;

    private String desc;

    ErrorCodeEnum(String code, String desc) {
        this.code = code;
        this.desc = desc;
    }

    public String getCode()
    {
        return this.code;
    }


    public String getDesc() {
        return desc;
    }
}
需要提供get set方法

**Comment by shalousun** [comment]
@caochaofeng @chishengfeng smart-doc的文档已经描述很清楚，smart-doc提供了很多的配置项，这些配置项需要根据自己的项目实际情况来配置，我们给的完整json是配置项使用参考，需要根据自己的项目调整，不需要的配置项可以不配置。
