### ISSUE TITLE
[feather request] 未找到configFile时报错提示

### ISSUE THREAD

**Issue by jetmit** [smart-doc-group/smart-doc-maven-plugin#5]
## Summary
希望在`configFile`未找到时有报错提示
### Basic example
<img width="504" alt="1_20201114071456" src="https://user-images.githubusercontent.com/20562449/99142061-6d8a7700-268c-11eb-821a-614759d7ffa1.png">

### Motivation
这里未找到`plugin`里配置的`configFile`直接返回了,没有提示和报错,`maven`显示`BUILD SUCCESS`却找不到`doc`
第一次使用时没想到这点对比几次文档才发现手误了,`configFile`的值和`resources`下不一样
这里加一个错误信息提示会友好很多,而且没有找到配置文件也没有`default.json`的情况下认为`BUILD SUCCESS`也不太合理

**Comment by shalousun** [comment]
经过测试，maven多目前项目中并不能使用抛出异常的方式
