### ISSUE TITLE
确认是可用的？

### ISSUE THREAD

**Issue by ewsq** [smart-doc-group/smart-doc-maven-plugin#7]
下载了：
https://gitee.com/sunyurepository/api-doc-test
无法使用起来，使用的版本与maven服务器上的根本不一致，并且文档写的maven引用都不一致，这开源不严肃，不认真
https://mvnrepository.com/artifact/com.github.shalousun/smart-doc/1.9.8
上的

<dependency>
    <groupId>com.github.shalousun</groupId>
    <artifactId>smart-doc</artifactId>
    <version>1.9.8</version>
</dependency>

而文档中的：
<groupId>com.github.shalousun</groupId>
<artifactId>smart-doc-maven-plugin</artifactId>
 <version>1.2.2</version>

这是两个不同的东西？？？

**Comment by shalousun** [comment]
@ewsq 请自己阅读文档，认真思考。smart-doc国内那么多用户，为什么这儿会提出这样的issue。年少犯错并不可怕，可怕的是不去思考
